// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _13_MyAcademy_JWT_Identity.Context;

#nullable disable

namespace _13_MyAcademy_JWT_Identity.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260301182550_FixMangaImageUrl")]
    partial class FixMangaImageUrl
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("_13_MyAcademy_JWT_Identity.Entities.Album", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ArtistId")
                        .HasColumnType("int");

                    b.Property<string>("CoverImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReleaseYear")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ArtistId");

                    b.ToTable("Albums");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArtistId = 1,
                            CoverImageUrl = "/bepop/assets/img/c0.jpg",
                            ReleaseYear = 2001,
                            Title = "Karma"
                        },
                        new
                        {
                            Id = 2,
                            ArtistId = 2,
                            CoverImageUrl = "/bepop/assets/img/c1.jpg",
                            ReleaseYear = 1991,
                            Title = "Gülümse"
                        },
                        new
                        {
                            Id = 3,
                            ArtistId = 3,
                            CoverImageUrl = "/bepop/assets/img/c2.jpg",
                            ReleaseYear = 1999,
                            Title = "Mançoloji"
                        },
                        new
                        {
                            Id = 4,
                            ArtistId = 1,
                            CoverImageUrl = "/bepop/assets/img/c3.jpg",
                            ReleaseYear = 2007,
                            Title = "Metamorfoz"
                        },
                        new
                        {
                            Id = 5,
                            ArtistId = 4,
                            CoverImageUrl = "/bepop/assets/img/c4.jpg",
                            ReleaseYear = 1977,
                            Title = "Superstar"
                        },
                        new
                        {
                            Id = 6,
                            ArtistId = 5,
                            CoverImageUrl = "/bepop/assets/img/c5.jpg",
                            ReleaseYear = 1977,
                            Title = "Resimdeki Gözyaşları"
                        },
                        new
                        {
                            Id = 7,
                            ArtistId = 6,
                            CoverImageUrl = "/bepop/assets/img/c6.jpg",
                            ReleaseYear = 2001,
                            Title = "Onyedi"
                        },
                        new
                        {
                            Id = 8,
                            ArtistId = 7,
                            CoverImageUrl = "/bepop/assets/img/c7.jpg",
                            ReleaseYear = 2003,
                            Title = "Every Way That I Can"
                        },
                        new
                        {
                            Id = 9,
                            ArtistId = 8,
                            CoverImageUrl = "/bepop/assets/img/c20.jpg",
                            ReleaseYear = 2008,
                            Title = "Hadise"
                        },
                        new
                        {
                            Id = 10,
                            ArtistId = 9,
                            CoverImageUrl = "/bepop/assets/img/c8.jpg",
                            ReleaseYear = 1988,
                            Title = "Kâğıt Helva"
                        },
                        new
                        {
                            Id = 11,
                            ArtistId = 10,
                            CoverImageUrl = "/bepop/assets/img/c9.jpg",
                            ReleaseYear = 2004,
                            Title = "Rapstar"
                        },
                        new
                        {
                            Id = 12,
                            ArtistId = 11,
                            CoverImageUrl = "/bepop/assets/img/c10.jpg",
                            ReleaseYear = 2020,
                            Title = "Darmaduman"
                        },
                        new
                        {
                            Id = 13,
                            ArtistId = 12,
                            CoverImageUrl = "/bepop/assets/img/c11.jpg",
                            ReleaseYear = 2006,
                            Title = "Bir Pesimistin Gözyaşları"
                        },
                        new
                        {
                            Id = 14,
                            ArtistId = 13,
                            CoverImageUrl = "/bepop/assets/img/c12.jpg",
                            ReleaseYear = 2004,
                            Title = "Dünya Yalan Söylüyor"
                        },
                        new
                        {
                            Id = 15,
                            ArtistId = 14,
                            CoverImageUrl = "/bepop/assets/img/c13.jpg",
                            ReleaseYear = 1985,
                            Title = "Nilüfer"
                        },
                        new
                        {
                            Id = 16,
                            ArtistId = 15,
                            CoverImageUrl = "/bepop/assets/img/c14.jpg",
                            ReleaseYear = 2008,
                            Title = "Ellerine Sağlık"
                        },
                        new
                        {
                            Id = 17,
                            ArtistId = 16,
                            CoverImageUrl = "/bepop/assets/img/c15.jpg",
                            ReleaseYear = 2010,
                            Title = "M.S. 05.03.2010"
                        },
                        new
                        {
                            Id = 18,
                            ArtistId = 17,
                            CoverImageUrl = "/bepop/assets/img/c16.jpg",
                            ReleaseYear = 1989,
                            Title = "Ele Güne Karşı"
                        },
                        new
                        {
                            Id = 19,
                            ArtistId = 18,
                            CoverImageUrl = "/bepop/assets/img/c17.jpg",
                            ReleaseYear = 2009,
                            Title = "Şehr-i Hüzün"
                        });
                });

            modelBuilder.Entity("_13_MyAcademy_JWT_Identity.Entities.AppRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("_13_MyAcademy_JWT_Identity.Entities.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int?>("PackageId")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("PackageId");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("_13_MyAcademy_JWT_Identity.Entities.Artist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Artists");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bio = "Türk pop müziğinin megastarı",
                            ImageUrl = "/bepop/assets/img/tarkan.jpg",
                            Name = "Tarkan"
                        },
                        new
                        {
                            Id = 2,
                            Bio = "Türk pop müziğinin minik serçesi",
                            ImageUrl = "/bepop/assets/img/sezenaksu.jpg",
                            Name = "Sezen Aksu"
                        },
                        new
                        {
                            Id = 3,
                            Bio = "Türk rock müziğinin efsanesi",
                            ImageUrl = "/bepop/assets/img/barışmanço.jpg",
                            Name = "Barış Manço"
                        },
                        new
                        {
                            Id = 4,
                            Bio = "Türk pop müziğinin süperstarı",
                            ImageUrl = "/bepop/assets/img/b7.jpg",
                            Name = "Ajda Pekkan"
                        },
                        new
                        {
                            Id = 5,
                            Bio = "Anadolu rock'ın öncüsü",
                            ImageUrl = "/bepop/assets/img/b8.jpg",
                            Name = "Cem Karaca"
                        },
                        new
                        {
                            Id = 6,
                            Bio = "Alternatif rock sanatçısı",
                            ImageUrl = "/bepop/assets/img/teoman.jpg",
                            Name = "Teoman"
                        },
                        new
                        {
                            Id = 7,
                            Bio = "Eurovision şampiyonu",
                            ImageUrl = "/bepop/assets/img/sertaperener.jpg",
                            Name = "Sertab Erener"
                        },
                        new
                        {
                            Id = 8,
                            Bio = "Pop ve R&B sanatçısı",
                            ImageUrl = "/bepop/assets/img/hadise.jpg",
                            Name = "Hadise"
                        },
                        new
                        {
                            Id = 9,
                            Bio = "Arabesk müziğin efsanevi sesi",
                            ImageUrl = "/bepop/assets/img/müslümgürses.jpg",
                            Name = "Müslüm Gürses"
                        },
                        new
                        {
                            Id = 10,
                            Bio = "Türk rap müziğinin öncüsü",
                            ImageUrl = "/bepop/assets/img/ceza.jpg",
                            Name = "Ceza"
                        },
                        new
                        {
                            Id = 11,
                            Bio = "Türk rock müziğinin sevilen grubu",
                            ImageUrl = "/bepop/assets/img/duman.jpg",
                            Name = "Duman"
                        },
                        new
                        {
                            Id = 12,
                            Bio = "Türk hip-hop sahnesinin usta ismi",
                            ImageUrl = "/bepop/assets/img/sagopa.jpg",
                            Name = "Sagopa Kajmer"
                        },
                        new
                        {
                            Id = 13,
                            Bio = "Alternatif rock'ın öncü grubu",
                            ImageUrl = "/bepop/assets/img/morveötesi.jpg",
                            Name = "Mor ve Ötesi"
                        },
                        new
                        {
                            Id = 14,
                            Bio = "Türk pop müziğinin divası",
                            ImageUrl = "/bepop/assets/img/nil.jpg",
                            Name = "Nilüfer"
                        },
                        new
                        {
                            Id = 15,
                            Bio = "Pop müziğin sevilen sesi",
                            ImageUrl = "/bepop/assets/img/yalın.jpg",
                            Name = "Yalın"
                        },
                        new
                        {
                            Id = 16,
                            Bio = "Pop rock'ın sevilen grubu",
                            ImageUrl = "/bepop/assets/img/gripin.jpg",
                            Name = "Gripin"
                        },
                        new
                        {
                            Id = 17,
                            Bio = "Türk pop-rock'ın efsane üçlüsü",
                            ImageUrl = "/bepop/assets/img/b12.jpg",
                            Name = "MFÖ"
                        },
                        new
                        {
                            Id = 18,
                            Bio = "Nu-metal ve alternatif rock grubu",
                            ImageUrl = "/bepop/assets/img/maaaaang.jpg",
                            Name = "Manga"
                        });
                });

            modelBuilder.Entity("_13_MyAcademy_JWT_Identity.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("_13_MyAcademy_JWT_Identity.Entities.Package", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ContentLevel")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Packages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContentLevel = 1,
                            Name = "Elite"
                        },
                        new
                        {
                            Id = 2,
                            ContentLevel = 2,
                            Name = "Premium"
                        },
                        new
                        {
                            Id = 3,
                            ContentLevel = 3,
                            Name = "Gold"
                        },
                        new
                        {
                            Id = 4,
                            ContentLevel = 4,
                            Name = "Standard"
                        },
                        new
                        {
                            Id = 5,
                            ContentLevel = 5,
                            Name = "Basic"
                        },
                        new
                        {
                            Id = 6,
                            ContentLevel = 6,
                            Name = "Free"
                        });
                });

            modelBuilder.Entity("_13_MyAcademy_JWT_Identity.Entities.Song", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AlbumId")
                        .HasColumnType("int");

                    b.Property<int>("ContentLevel")
                        .HasColumnType("int");

                    b.Property<int>("DurationInSeconds")
                        .HasColumnType("int");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId");

                    b.ToTable("Songs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AlbumId = 1,
                            ContentLevel = 6,
                            DurationInSeconds = 234,
                            FilePath = "songs/simarik.mp3",
                            Title = "Şımarık"
                        },
                        new
                        {
                            Id = 2,
                            AlbumId = 1,
                            ContentLevel = 5,
                            DurationInSeconds = 258,
                            FilePath = "songs/kuzukuzu.mp3",
                            Title = "Kuzu Kuzu"
                        },
                        new
                        {
                            Id = 3,
                            AlbumId = 1,
                            ContentLevel = 4,
                            DurationInSeconds = 245,
                            FilePath = "songs/dudu.mp3",
                            Title = "Dudu"
                        },
                        new
                        {
                            Id = 4,
                            AlbumId = 2,
                            ContentLevel = 3,
                            DurationInSeconds = 300,
                            FilePath = "songs/gulumse.mp3",
                            Title = "Gülümse"
                        },
                        new
                        {
                            Id = 5,
                            AlbumId = 2,
                            ContentLevel = 2,
                            DurationInSeconds = 275,
                            FilePath = "songs/hadibakalim.mp3",
                            Title = "Hadi Bakalım"
                        },
                        new
                        {
                            Id = 6,
                            AlbumId = 3,
                            ContentLevel = 1,
                            DurationInSeconds = 312,
                            FilePath = "songs/gesibaglari.mp3",
                            Title = "Gesi Bağları"
                        },
                        new
                        {
                            Id = 7,
                            AlbumId = 3,
                            ContentLevel = 6,
                            DurationInSeconds = 290,
                            FilePath = "songs/donence.mp3",
                            Title = "Dönence"
                        },
                        new
                        {
                            Id = 8,
                            AlbumId = 3,
                            ContentLevel = 4,
                            DurationInSeconds = 267,
                            FilePath = "songs/allabeni.mp3",
                            Title = "Alla Beni Pulla Beni"
                        },
                        new
                        {
                            Id = 9,
                            AlbumId = 4,
                            ContentLevel = 5,
                            DurationInSeconds = 215,
                            FilePath = "songs/bounce.mp3",
                            Title = "Bounce"
                        },
                        new
                        {
                            Id = 10,
                            AlbumId = 4,
                            ContentLevel = 4,
                            DurationInSeconds = 225,
                            FilePath = "songs/dedikodu.mp3",
                            Title = "Dedikodu"
                        },
                        new
                        {
                            Id = 11,
                            AlbumId = 5,
                            ContentLevel = 3,
                            DurationInSeconds = 198,
                            FilePath = "songs/superstar.mp3",
                            Title = "Superstar"
                        },
                        new
                        {
                            Id = 12,
                            AlbumId = 5,
                            ContentLevel = 6,
                            DurationInSeconds = 210,
                            FilePath = "songs/bambaska.mp3",
                            Title = "Bambaşka Biri"
                        },
                        new
                        {
                            Id = 13,
                            AlbumId = 6,
                            ContentLevel = 2,
                            DurationInSeconds = 245,
                            FilePath = "songs/tamirci.mp3",
                            Title = "Tamirci Çırağı"
                        },
                        new
                        {
                            Id = 14,
                            AlbumId = 6,
                            ContentLevel = 1,
                            DurationInSeconds = 280,
                            FilePath = "songs/resimdeki.mp3",
                            Title = "Resimdeki Gözyaşları"
                        },
                        new
                        {
                            Id = 15,
                            AlbumId = 7,
                            ContentLevel = 4,
                            DurationInSeconds = 235,
                            FilePath = "songs/istanbul.mp3",
                            Title = "İstanbul'da Sonbahar"
                        },
                        new
                        {
                            Id = 16,
                            AlbumId = 7,
                            ContentLevel = 5,
                            DurationInSeconds = 205,
                            FilePath = "songs/papatya.mp3",
                            Title = "Papatya"
                        },
                        new
                        {
                            Id = 17,
                            AlbumId = 8,
                            ContentLevel = 3,
                            DurationInSeconds = 180,
                            FilePath = "songs/everyway.mp3",
                            Title = "Every Way That I Can"
                        },
                        new
                        {
                            Id = 18,
                            AlbumId = 8,
                            ContentLevel = 6,
                            DurationInSeconds = 220,
                            FilePath = "songs/leave.mp3",
                            Title = "Leave"
                        },
                        new
                        {
                            Id = 19,
                            AlbumId = 9,
                            ContentLevel = 6,
                            DurationInSeconds = 178,
                            FilePath = "songs/dumtek.mp3",
                            Title = "Düm Tek Tek"
                        },
                        new
                        {
                            Id = 20,
                            AlbumId = 9,
                            ContentLevel = 4,
                            DurationInSeconds = 195,
                            FilePath = "songs/superman.mp3",
                            Title = "Superman"
                        },
                        new
                        {
                            Id = 21,
                            AlbumId = 10,
                            ContentLevel = 5,
                            DurationInSeconds = 310,
                            FilePath = "songs/kagithelva.mp3",
                            Title = "Kâğıt Helva"
                        },
                        new
                        {
                            Id = 22,
                            AlbumId = 10,
                            ContentLevel = 3,
                            DurationInSeconds = 285,
                            FilePath = "songs/affet.mp3",
                            Title = "Affet"
                        },
                        new
                        {
                            Id = 23,
                            AlbumId = 11,
                            ContentLevel = 2,
                            DurationInSeconds = 248,
                            FilePath = "songs/holocaust.mp3",
                            Title = "Holocaust"
                        },
                        new
                        {
                            Id = 24,
                            AlbumId = 11,
                            ContentLevel = 6,
                            DurationInSeconds = 230,
                            FilePath = "songs/neyimvarki.mp3",
                            Title = "Neyim Var Ki"
                        },
                        new
                        {
                            Id = 25,
                            AlbumId = 12,
                            ContentLevel = 4,
                            DurationInSeconds = 256,
                            FilePath = "songs/sendendahaguzel.mp3",
                            Title = "Senden Daha Güzel"
                        },
                        new
                        {
                            Id = 26,
                            AlbumId = 12,
                            ContentLevel = 6,
                            DurationInSeconds = 242,
                            FilePath = "songs/yurekten.mp3",
                            Title = "Yürekten"
                        },
                        new
                        {
                            Id = 27,
                            AlbumId = 13,
                            ContentLevel = 1,
                            DurationInSeconds = 268,
                            FilePath = "songs/baytar.mp3",
                            Title = "Baytar"
                        },
                        new
                        {
                            Id = 28,
                            AlbumId = 13,
                            ContentLevel = 5,
                            DurationInSeconds = 295,
                            FilePath = "songs/dusunki.mp3",
                            Title = "Düşün Ki"
                        },
                        new
                        {
                            Id = 29,
                            AlbumId = 14,
                            ContentLevel = 6,
                            DurationInSeconds = 218,
                            FilePath = "songs/cambaz.mp3",
                            Title = "Cambaz"
                        },
                        new
                        {
                            Id = 30,
                            AlbumId = 14,
                            ContentLevel = 3,
                            DurationInSeconds = 240,
                            FilePath = "songs/dunyayalan.mp3",
                            Title = "Dünya Yalan Söylüyor"
                        },
                        new
                        {
                            Id = 31,
                            AlbumId = 15,
                            ContentLevel = 4,
                            DurationInSeconds = 230,
                            FilePath = "songs/dunyadonuyor.mp3",
                            Title = "Dünya Dönüyor"
                        },
                        new
                        {
                            Id = 32,
                            AlbumId = 15,
                            ContentLevel = 6,
                            DurationInSeconds = 255,
                            FilePath = "songs/geceler.mp3",
                            Title = "Geceler"
                        },
                        new
                        {
                            Id = 33,
                            AlbumId = 16,
                            ContentLevel = 5,
                            DurationInSeconds = 220,
                            FilePath = "songs/ellerinesaglik.mp3",
                            Title = "Ellerine Sağlık"
                        },
                        new
                        {
                            Id = 34,
                            AlbumId = 16,
                            ContentLevel = 2,
                            DurationInSeconds = 238,
                            FilePath = "songs/asklaftan.mp3",
                            Title = "Aşk Laftan Anlamaz"
                        },
                        new
                        {
                            Id = 35,
                            AlbumId = 17,
                            ContentLevel = 6,
                            DurationInSeconds = 252,
                            FilePath = "songs/boylekahpe.mp3",
                            Title = "Böyle Kahpedir Dünya"
                        },
                        new
                        {
                            Id = 36,
                            AlbumId = 17,
                            ContentLevel = 3,
                            DurationInSeconds = 227,
                            FilePath = "songs/durmayagmur.mp3",
                            Title = "Durma Yağmur Durma"
                        },
                        new
                        {
                            Id = 37,
                            AlbumId = 18,
                            ContentLevel = 4,
                            DurationInSeconds = 210,
                            FilePath = "songs/elegunekarsi.mp3",
                            Title = "Ele Güne Karşı"
                        },
                        new
                        {
                            Id = 38,
                            AlbumId = 18,
                            ContentLevel = 6,
                            DurationInSeconds = 198,
                            FilePath = "songs/alidesidero.mp3",
                            Title = "Ali Desidero"
                        },
                        new
                        {
                            Id = 39,
                            AlbumId = 19,
                            ContentLevel = 1,
                            DurationInSeconds = 235,
                            FilePath = "songs/dunyaninsonu.mp3",
                            Title = "Dünyanın Sonuna Doğmuşum"
                        },
                        new
                        {
                            Id = 40,
                            AlbumId = 19,
                            ContentLevel = 5,
                            DurationInSeconds = 248,
                            FilePath = "songs/birkadin.mp3",
                            Title = "Bir Kadın Çizeceksin"
                        });
                });

            modelBuilder.Entity("_13_MyAcademy_JWT_Identity.Entities.UserSongHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("PlayedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("SongId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SongId");

                    b.HasIndex("UserId");

                    b.ToTable("UserSongHistories");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("_13_MyAcademy_JWT_Identity.Entities.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("_13_MyAcademy_JWT_Identity.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("_13_MyAcademy_JWT_Identity.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("_13_MyAcademy_JWT_Identity.Entities.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_13_MyAcademy_JWT_Identity.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("_13_MyAcademy_JWT_Identity.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("_13_MyAcademy_JWT_Identity.Entities.Album", b =>
                {
                    b.HasOne("_13_MyAcademy_JWT_Identity.Entities.Artist", "Artist")
                        .WithMany("Albums")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("_13_MyAcademy_JWT_Identity.Entities.AppUser", b =>
                {
                    b.HasOne("_13_MyAcademy_JWT_Identity.Entities.Package", "Package")
                        .WithMany("Users")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Package");
                });

            modelBuilder.Entity("_13_MyAcademy_JWT_Identity.Entities.Song", b =>
                {
                    b.HasOne("_13_MyAcademy_JWT_Identity.Entities.Album", "Album")
                        .WithMany("Songs")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Album");
                });

            modelBuilder.Entity("_13_MyAcademy_JWT_Identity.Entities.UserSongHistory", b =>
                {
                    b.HasOne("_13_MyAcademy_JWT_Identity.Entities.Song", "Song")
                        .WithMany("UserSongHistories")
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_13_MyAcademy_JWT_Identity.Entities.AppUser", "User")
                        .WithMany("UserSongHistories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Song");

                    b.Navigation("User");
                });

            modelBuilder.Entity("_13_MyAcademy_JWT_Identity.Entities.Album", b =>
                {
                    b.Navigation("Songs");
                });

            modelBuilder.Entity("_13_MyAcademy_JWT_Identity.Entities.AppUser", b =>
                {
                    b.Navigation("UserSongHistories");
                });

            modelBuilder.Entity("_13_MyAcademy_JWT_Identity.Entities.Artist", b =>
                {
                    b.Navigation("Albums");
                });

            modelBuilder.Entity("_13_MyAcademy_JWT_Identity.Entities.Package", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("_13_MyAcademy_JWT_Identity.Entities.Song", b =>
                {
                    b.Navigation("UserSongHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
